# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('uf', models.CharField(db_column='ads_uf', max_length=2)),
                ('city', models.CharField(db_column='ads_city', max_length=255)),
                ('neighborhood', models.CharField(db_column='ads_neighborhood', max_length=255)),
                ('street', models.CharField(db_column='ads_street', max_length=255)),
                ('complement', models.CharField(db_column='ads_complement', max_length=50)),
                ('number', models.CharField(db_column='ads_number', max_length=10)),
                ('cep', models.CharField(db_column='ads_cep', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='ads_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='ads_updated_at')),
                ('company', models.ForeignKey(db_column='ads_company', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('property', models.ForeignKey(db_column='ads_property', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
            options={
                'db_table': 'tbl_addresses',
            },
        ),
    ]
