# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotSchedulesProperties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='puc_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='puc_updated_at')),
                ('property', models.ForeignKey(db_column='puc_id_property_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
            ],
            options={
                'db_table': 'tbl_pivot_schedules_properties',
            },
        ),
    ]
