# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(db_column='usr_first_name', max_length=255)),
                ('last_name', models.CharField(db_column='usr_last_name', max_length=255)),
                ('birthdate', models.DateField(db_column='usr_birthdate', default=None, null=True)),
                ('cpf', models.CharField(db_column='usr_cpf', max_length=11, unique=True)),
                ('email', models.EmailField(db_column='usr_email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='usr_password', max_length=255)),
                ('phone', models.CharField(db_column='usr_phone', max_length=50)),
                ('is_superuser', models.BooleanField(db_column='usr_is_superuser', default=False)),
                ('is_active', models.BooleanField(db_column='usr_is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='usr_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='usr_updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
