# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occupations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotOccupationsUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='pou_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='pou_updated_at')),
                ('occupation', models.ForeignKey(db_column='pou_id_occupation_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='occupations.occupation')),
            ],
            options={
                'db_table': 'tbl_pivot_occupations_users',
            },
        ),
    ]
