# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pivot_occupations_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pivotoccupationsusers',
            name='user',
            field=models.ForeignKey(db_column='pou_id_user_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
