# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dba', models.CharField(db_column='cpy_dba', max_length=255)),
                ('corporate_name', models.CharField(db_column='cpy_corporate_name', max_length=255)),
                ('municipal_registration', models.CharField(db_column='cpy_municipal_registration', max_length=14)),
                ('state_registration', models.CharField(db_column='cpy_state_registration', max_length=14)),
                ('email', models.EmailField(db_column='cpy_email', max_length=255)),
                ('phone', models.CharField(db_column='cpy_phone', max_length=11)),
                ('cnpj', models.CharField(db_column='cpy_cnpj', max_length=14, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='cpy_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='cpy_updated_at')),
            ],
            options={
                'db_table': 'tbl_companies',
            },
        ),
    ]
