# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('comments', models.TextField(db_column='sch_comments')),
                ('status_schedule', models.SmallIntegerField(db_column='sch_status_schedule')),
                ('start_time', models.DateTimeField(db_column='sch_start_time')),
                ('end_time', models.DateTimeField(db_column='sch_end_time')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='sch_created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='sch_updated_at')),
            ],
            options={
                'db_table': 'tbl_schedules',
            },
        ),
    ]
