# Generated by Django 4.0.6 on 2022-07-19 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='broker',
            field=models.ForeignKey(db_column='puc_id_broker_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='client',
            field=models.ForeignKey(db_column='puc_id_client_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='company',
            field=models.ForeignKey(db_column='puc_id_company_fk', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
